-- ============================================================
-- ElectroShop — product catalogue data backup
-- 479 products, reconstructed from the cleaned import file
-- Target table: products (MySQL 8). Safe to load into a fresh schema.
-- ============================================================
SET NAMES utf8mb4;

-- Optional: start from a clean catalogue (keeps schema, clears rows).
-- DELETE FROM product_images;
-- DELETE FROM products;

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Vasco Translator V4 - Translator AI Vocal/Foto + Internet Gratuit pentru Traduceri', NULL, 1800.0, 1, 'Traducatoare', 'Translatoare AI', 'Vasco', 1100.0, NULL, NULL, NOW(), NOW()),
  ('Uscator De Par Severin S-Style „Speed Pro”, 2.000 W, Antracit, Hc 0169', NULL, 200.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Severin', 100.0, NULL, NULL, NOW(), NOW()),
  ('Trotineta electrica Ninebot by Segway KickScooter MAX G2, Viteza maxima 20 Km/h, Autonomie 50-70 Km, Motor 450 W, IPX5, Bluetooth, Roti 10" (Gri)', NULL, 2800.0, 7, 'Auto & Moto', 'Auto & Moto', 'Segway', 1978.57, NULL, NULL, NOW(), NOW()),
  ('Trimmer pentru nas/urechi PHILIPS NT3650/16, baterie, lavabil, tehnologie Precision Trim, otel inoxidabil, pieptene pentru sprancene, pieptene 5 mm, Gri', NULL, 25.0, 60, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 10.0, NULL, NULL, NOW(), NOW()),
  ('Televizor Sony BRAVIA 8 OLED 65XR80, 164 cm, Smart Google TV, 4K Ultra HD, 100 Hz, Clasa E', NULL, 5500.0, 1, 'TV & Proiectoare', 'Televizoare', 'Sony', 4200.0, NULL, NULL, NOW(), NOW()),
  ('Televizor Mini-LED ULED Smart HISENSE 65U8Q, Ultra HD 4K,164cm', NULL, 4000.0, 1, 'TV & Proiectoare', 'Televizoare', NULL, 2550.0, NULL, NULL, NOW(), NOW()),
  ('Televizor LG 55QNED82A6B 55" 4K QNED AI TV (α7 Gen8 4K AI Processor, 25 WebOS, 60 Hz) Model Year 2025', NULL, 2200.0, 1, 'TV & Proiectoare', 'Televizoare', NULL, 1400.0, NULL, NULL, NOW(), NOW()),
  ('Televizor LED Smart TCL 55V6C, diagonala 139 cm, Ultra HD / 4K, clasa E, sistem operare Google TV, tehnologie HDR, Dolby Audio, Chromecast, T-Cast, Game Mode, negru', NULL, 1000.0, 1, 'TV & Proiectoare', 'Televizoare', 'Google', 650.0, NULL, NULL, NOW(), NOW()),
  ('Telemetru cu laser Mileseey S50', NULL, 300.0, 1, 'Foto & Video', 'Optica', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Telefon view BV9300 Orange, 4G, 6.7" FHD+ 120Hz, 12GB+ 9GB RAM, 256GB+1TB ROM, Android 12, NFC, 15080mAh, Dual SIM', NULL, 850.0, 1, 'Telefoane', 'Telefoane', NULL, 700.0, NULL, NULL, NOW(), NOW()),
  ('Telefon view BV8100, 4G, 6.5" 2.4K FHD+, 24GB RAM (8GB + 16GB extensibili), 256GB ROM, Android 14, MediaTek Helio G99, 50MP+32MP, 8800mAh, 45W, NFC, Dual SIM', NULL, 650.0, 1, 'Telefoane', 'Telefoane', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Unihertz Jelly Max , 5G, 5.05", 12GB RAM, 256GB ROM, Android 14, Dimensity 7300 Octa-Core, Bt v5.4, NFC, 4000mAh, Dual SIM', NULL, 900.0, 1, 'Telefoane', 'Telefoane', NULL, 750.0, NULL, NULL, NOW(), NOW()),
  ('Telefon SOYES XS19 Pro 4GB RAM 64GB ROM 3.88 Inch Mini telefon 4G Android', NULL, 200.0, 2, 'Telefoane', 'Telefoane', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Telefon seniori doro leva l10', NULL, 125.0, 8, 'Telefoane', 'Telefoane', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Oukitel WP56, Dual SIM, 5G, Octa-Core Dimensity 7050, 6.8-inch 120Hz IPS, 8+24GB RAM, 256GB, Lanterna SOS Puternica, NFC, 16000mAh, 45W, IP68/IP69K, Android 15,', NULL, 1000.0, 1, 'Accesorii', 'Lanterne', NULL, 600.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Oukitel WP55 Pro, Orange, 5G, 6.6" FHD+ 120Hz, 48GB RAM (16GB+32GB Extensibili), 512GB ROM, Android 15, Dimensity 7025, 108MP+32MP, Vedere nocturna, NFC, Face ID, 11000mAh, 33W, Dual SIM', NULL, 1000.0, 1, 'Telefoane', 'Telefoane', NULL, 700.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Oukitel WP55 Pro, , 5G, 6.6" FHD+ 120Hz, 48GB RAM (16GB+32GB Extensibili), 512GB ROM, Android 15, Dimensity 7025, 108MP+32MP, Vedere nocturna, NFC, Face ID, 11000mAh, 33W, Dual SIM', NULL, 1000.0, 1, 'Telefoane', 'Telefoane', NULL, 700.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Oukitel WP35, Dual SIM, 5G, Octa-Core Dimensity 6100+, 6.6-inch 2.4K IPS, 24GB RAM, 256GB, NFC, 11000mAh, IP68/IP69K, Android 14, Grey', NULL, 600.0, 1, 'Telefoane', 'Telefoane', NULL, 375.0, NULL, NULL, NOW(), NOW()),
  ('Telefon mobil Google Pixel 10a,128GB, 8GB RAM, 5G', NULL, 1800.0, 1, 'Telefoane', 'Telefoane', 'Google', 1200.0, NULL, NULL, NOW(), NOW()),
  ('Telefon folosit Motorola Moto g56, 8GB RAM, 256GB, 5G, Black Oyster - resigilat', NULL, 500.0, 1, 'Auto & Moto', 'Auto & Moto', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('Telefon emporia Smart.7 lite', NULL, 700.0, 1, 'Telefoane', 'Telefoane', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Doogee S200X, Gri, 5G, Dual Display (6.72"+1.32") 2.4K AMOLED, Functii AI Foto, 12GB RAM (12GB + 20GB extensibili), 512GB ROM, 100MP, Android 14, Dimensity 7050, 10100mAh, Dual SIM', NULL, 1000.0, 1, 'TV & Proiectoare', 'Televizoare', NULL, 750.0, NULL, NULL, NOW(), NOW()),
  ('Telefon brondi stone+', NULL, 100.0, 1, 'Telefoane', 'Telefoane', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Brondi Amico vero 4g 5,7inch, 3/32gb', NULL, 200.0, 3, 'Telefoane', 'Telefoane', NULL, 0.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Becindy Mini Phone XS18Pro 3.0 Inch HD 2GB+16GB', NULL, 100.0, 1, 'Telefoane', 'Telefoane', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Telefon Apple Iphone 17 pro 256gb Orange', NULL, 5400.0, 1, 'Telefoane', 'Telefoane', 'Apple', 5300.0, NULL, NULL, NOW(), NOW()),
  ('Telefon AGM MOBILE H MAX Rugged 128GB 4GB RAM Dual SIM Negru', NULL, 600.0, 1, 'Telefoane', 'Telefoane', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('Tastatura Microsoft Surface Pro Flex Keyboard + Slim Pen 2, Compatibila cu Surface Pro 11/10/9/8 qwertz', NULL, 1000.0, 1, 'Periferice PC', 'Periferice', 'Microsoft', 750.0, NULL, NULL, NOW(), NOW()),
  ('Tastatura Magic Keyboard (USB-C) - Danish mxcl3dk/a', NULL, 300.0, 5, 'Periferice PC', 'Periferice', NULL, 225.0, NULL, NULL, NOW(), NOW()),
  ('Tastatura Apple Magic, Touch ID, Numeric Keypad White Keys', NULL, 500.0, 1, 'Periferice PC', 'Periferice', 'Apple', 300.0, NULL, NULL, NOW(), NOW()),
  ('Tableta grafica XP-PEN Deco PRO LW Gen 2, 11x7", 16384 niveluri presiune, conexiune Bluetooth 5.0, Pen-Stand, 10 varfuri de rezerva, cu telecomanda ACK05', NULL, 650.0, 7, 'Tablete', 'Tablete', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('Tableta Folosita APPLE iPad 11" (A16), 256GB, Wi-Fi, Silver - impecabila 0 cicluri doar activata!', NULL, 1600.0, 1, 'Tablete', 'Tablete', 'Apple', 1100.0, NULL, NULL, NOW(), NOW()),
  ('Tabletă E-Ink Boox Palma 2 Pro, 6.13 inch, 8GB RAM, 128GB, Dual SIM, Negru + husa', NULL, 1500.0, 1, 'Tablete', 'Tablete', NULL, 1050.0, NULL, NULL, NOW(), NOW()),
  ('Tableta APPLE iPad Pro 11" (M5), 2TB, 16GB RAM, Wi-Fi, Standard Glass, Space Black', NULL, 9500.0, 1, 'Tablete', 'Tablete', 'Apple', 7500.0, NULL, NULL, NOW(), NOW()),
  ('Tableta Apple iPad mini 7 (2024), 128GB, Wi-Fi, Space Grey', NULL, 2000.0, 1, 'Tablete', 'Tablete', 'Apple', 1500.0, NULL, NULL, NOW(), NOW()),
  ('Tableta Apple iPad Air 13, M4, 128GB, Wi-Fi, Space Grey', NULL, 3500.0, 2, 'Tablete', 'Tablete', 'Apple', 2800.0, NULL, NULL, NOW(), NOW()),
  ('Tableta Apple iPad Air 11, M3, 256GB, Wi-Fi + Cellular, Space Grey', NULL, 3500.0, 1, 'Tablete', 'Tablete', 'Apple', 2700.0, NULL, NULL, NOW(), NOW()),
  ('Tableta Apple iPad Air 11, M3, 128GB, Wi-Fi, Silver', NULL, 2200.0, 5, 'Tablete', 'Tablete', 'Apple', 1800.0, NULL, NULL, NOW(), NOW()),
  ('Tableta APPLE iPad Air 11" (M4), 256GB, Wi-Fi,', NULL, 3000.0, 2, 'Tablete', 'Tablete', 'Apple', 2425.0, NULL, NULL, NOW(), NOW()),
  ('SwitchBot Lock Ultra Touch Combo', NULL, 700.0, 1, 'Smart Home', 'Smart Home', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Sursa iFi Audio iPower Elite 12v', NULL, 700.0, 1, 'Audio', 'Mixere & Interfete', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Suport extensie DJI Osmo Action Mini (trepied 2 în 1)', NULL, 125.0, 4, 'Foto & Video', 'Camere de actiune', 'DJI', 75.0, NULL, NULL, NOW(), NOW()),
  ('Streamer Wi-Fi WiiM Pro, 24bit /192kHz, Bluetooth 5.2, AUX, SPDIF, Spotify si Tidal Connect, Airplay 2', NULL, 550.0, 14, 'Audio', 'Mixere & Interfete', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Statie meteo Ecowitt HP2564 Wittboy Pro Weather Station, Includes HP2560_C TFT Display Console and WS90 Outdoor Solar Powered Weather Sensor', NULL, 900.0, 1, 'Gaming', 'Gaming', 'HP', 400.0, NULL, NULL, NOW(), NOW()),
  ('Statie de abur, Philips, PerfectCare Compact GC7844/20, 2400 W, 6,5 bar, pana la 400 g injectare de abur, rezervor de apa de 1,5 l', NULL, 500.0, 4, 'Electrocasnice', 'Electrocasnice', 'Philips', 300.0, NULL, NULL, NOW(), NOW()),
  ('StarTech 4-Port High Resolution USB DVI Dual Link KVM Switch with Audio ()', NULL, 1000.0, 1, 'Periferice PC', 'Periferice', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Stabilizator imagine DJI Osmo Mobile 7P, Bluetooth, 3 axe, extensibil, negru', NULL, 500.0, 1, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 300.0, NULL, NULL, NOW(), NOW()),
  ('SSD Western Digital SN7100 , NVMe™ M.2, 2TB', NULL, 1000.0, 1, 'Stocare', 'Stocare & Memorie', NULL, 650.0, NULL, NULL, NOW(), NOW()),
  ('SSD Sandisk optimus 5100 1tb', NULL, 500.0, 8, 'Stocare', 'Stocare & Memorie', 'Sandisk', 400.0, NULL, NULL, NOW(), NOW()),
  ('SSD portabil LaCie Rugged Mini SSD 4TB, USB-C 3.2, 2.5 inch, Orange', NULL, 1650.0, 2, 'Stocare', 'Stocare & Memorie', NULL, 1600.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('SSD Extern SanDisk Extreme PRO V2, 2TB, NVMe, USB 3.2 Gen2x2, Aluminiu, protectie IP55, gri/portocaliu', NULL, 1200.0, 1, 'Stocare', 'Stocare & Memorie', 'Sandisk', 800.0, NULL, NULL, NOW(), NOW()),
  ('SSD Crucial P3 Plus 4TB PCI Express 4.0 x4 M.2 2280', NULL, 1250.0, 1, 'Stocare', 'Stocare & Memorie', NULL, 1000.0, NULL, NULL, NOW(), NOW()),
  ('Soundbar SAMSUNG HW-S67D', NULL, 750.0, 20, 'Audio', 'Boxe & Soundbar', 'Samsung', 550.0, NULL, NULL, NOW(), NOW()),
  ('Sonerie Video Doorbell Ring Plus Battery', NULL, 200.0, 4, 'Smart Home', 'Camere supraveghere', 'Ring', 200.0, NULL, NULL, NOW(), NOW()),
  ('Sonerie video Blink Doorbell HD', NULL, 150.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 100.0, NULL, NULL, NOW(), NOW()),
  ('Sonar Deeper Smart Sonar Start', NULL, 350.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Xiaomi Watch S3,', NULL, 450.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Xiaomi', 375.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Samsung Galaxy Watch8 BT 44mm Graphite', NULL, 800.0, 2, 'Wearables', 'Smartwatch & Ceasuri', 'Samsung', 550.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Samsung Galaxy Watch 8, 40mm, Bluetooth, Silver', NULL, 750.0, 3, 'Wearables', 'Smartwatch & Ceasuri', 'Samsung', 550.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Pixel Watch 3 45mm Obsidian RESIGILAT - fara urme de uzura', NULL, 600.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Liu Jo Voice Slim 2.0 SWLJ198', NULL, 300.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Liu Jo', 250.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Kospet Tank T4 Negru', NULL, 550.0, 6, 'Wearables', 'Smartwatch & Ceasuri', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Kospet MAGIC P10, argintiu, GPS, ecran AMOLED, rezist la apa 5 ATM, peste 180 de moduri sportive', NULL, 450.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 225.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch knauermann pro 3', NULL, 300.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 125.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Huawei Watch GT 5, 41MM, White Steel Case, White Composite Leather Strap', NULL, 600.0, 2, 'Wearables', 'Smartwatch & Ceasuri', 'Huawei', 400.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch HUAWEI Watch 5 42mm, Stainless Steel Case with White Composite Strap, Health Glance, GPS', NULL, 1200.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Huawei', 800.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Garmin quatix 7 Pro 47mm Amoled Sapphire', NULL, 2300.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Garmin', 2100.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Garmin Instinct E 40 mm', NULL, 500.0, 2, 'Wearables', 'Smartwatch & Ceasuri', 'Garmin', 450.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Garmin Instinct 3 AMOLED 50mm', NULL, 1300.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Garmin', 900.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Garmin Descent G2 45 mm AMOLED negru', NULL, 2200.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Garmin', 1600.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch folosit Withings Scanwatch Nova 42mm - Albastru - Folosit FARA CUTIE', NULL, 1000.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 750.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Fitbit Versa 4 Black/Graphite 1.58 inch Aluminum', NULL, 400.0, 2, 'Wearables', 'Smartwatch & Ceasuri', 'Fitbit', 350.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch Fitbit Sense 2 Shadow Grey/Graphite Aluminum', NULL, 700.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Fitbit', 550.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch COROS PACE 3 GPS Sport Watch White', NULL, 700.0, 14, 'Auto & Moto', 'GPS & Navigatie', NULL, 600.0, NULL, NULL, NOW(), NOW()),
  ('Smartwatch AMAZFIT Active 2, GPS, Android/iOS resigilat lipsa curele/incarcator', NULL, 250.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Amazfit', 200.0, NULL, NULL, NOW(), NOW()),
  ('Smart Ring SAMSUNG Galaxy Ring, Size 14, Titanium', NULL, 650.0, 1, 'Wearables', 'Smart Rings', 'Samsung', 500.0, NULL, NULL, NOW(), NOW()),
  ('SmallRig RM120 Long-Battery-Life RGB Video Light 3808', NULL, 200.0, 1, 'Foto & Video', 'Accesorii foto-video', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('smallrig mobile video kit single handheld', NULL, 100.0, 1, 'Foto & Video', 'Accesorii foto-video', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('SmallRig 5002 Brandon Li Co Design Kit Lightweight Video pentru iPhone 16 Pro', NULL, 700.0, 1, 'Foto & Video', 'Accesorii foto-video', 'iPhone', 300.0, NULL, NULL, NOW(), NOW()),
  ('SmallRig 4597 Video Kit pentru Smartphone Editia Creators Quick Basic', NULL, 350.0, 1, 'Foto & Video', 'Accesorii foto-video', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('SmallRig 3575 Mini Matte Box Lite', NULL, 150.0, 1, 'Foto & Video', 'Accesorii foto-video', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Sistem parcare auto-vox make driving safe smart', NULL, 150.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Sistem Interfon Tmezon video door phone intercom system', NULL, 500.0, 1, 'Auto & Moto', 'Auto & Moto', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Sistem Filtrare Apa Vortopt DR2-White-1000GPD Reverse Osmosis System Water Filter - Under Sink Water Purifier, Tankless RO Water Filter System, 0.0001um Purification for Drinking, Reduces TDS, Vortopt', NULL, 800.0, 4, 'Electrocasnice', 'Electrocasnice', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de Stabilizare pentru Telefon DJI Osmo Mobile 8 - Folosite', NULL, 400.0, 2, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 300.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de Stabilizare pentru Telefon DJI Osmo Mobile 8', NULL, 500.0, 1, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 250.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de stabilizare DJI Osmo Mobile 7P, Negru', NULL, 500.0, 2, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 250.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de stabilizare DJI Osmo Mobile 7P, Negru', NULL, 350.0, 1, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 250.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de navigatie TomTom Go Classic, 5", Europe, Wi-Fi, Actualizari Traffic,', NULL, 300.0, 2, 'Auto & Moto', 'GPS & Navigatie', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de navigatie Garmin DriveSmart 66 EU MT-D, GPS , ecran 6", Wi-Fi, Bluetooth, Live traffic via digital traffic', NULL, 750.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Garmin', 550.0, NULL, NULL, NOW(), NOW()),
  ('Sistem de comunicare moto Midland BTX1 PRO S Dual Pack, Dual Core, Conferinta de pana la 3 rideri simultan, distanta 800m', NULL, 700.0, 1, 'Auto & Moto', 'Auto & Moto', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Sirena Ubiquiti UP-Siren Siren PoE', NULL, 300.0, 1, 'Smart Home', 'Smart Home', 'Ubiquiti', 250.0, NULL, NULL, NOW(), NOW()),
  ('Sirena de exterior, wireless, 868 MHz, LED cu lumina rosie, 113 dB, AJAX STREETSIREN WH', NULL, 500.0, 1, 'Smart Home', 'Smart Home', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Set panou de control Smart Shelly Wall Display si senzor de temperatura si umiditate BLU H&T, Bluetooth 4.2, WiFi,', NULL, 350.0, 5, 'Smart Home', 'Smart Home', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Set Hori Fighting Stick Alpha (Tekken 8 Edition) pentru PS5/PS4/PC', NULL, 600.0, 1, 'Gaming', 'Gaming', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Set 4 camere supraveghere exterior Blink Outdoor si Sync Module, Wireless, HD, senzor de miscare, compatibil Alexa, negre', NULL, 600.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 425.0, NULL, NULL, NOW(), NOW()),
  ('Sena Parani A20 Bluetooth Intercom Headset', NULL, 200.0, 1, 'Auto & Moto', 'Auto & Moto', 'Sena', 150.0, NULL, NULL, NOW(), NOW()),
  ('SCZND Instant Voice Translator,', NULL, 150.0, 1, 'Traducatoare', 'Translatoare AI', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('SAMSUNG Galaxy Tab S10+ Book Cover Keyboard AI Key, Detachable Platform, PC-Like Experience, Adjustable Viewing Angles, Wireless Keyboard Sharing, US Version,', NULL, 300.0, 2, 'Periferice PC', 'Periferice', 'Samsung', 150.0, NULL, NULL, NOW(), NOW()),
  ('RunCam Scope Cam 2 4K SCOPECAM2-4K-L40 Aluminium housing IP64 Waterproof 4XDigital Zoom 30fps Airsoft Tactical Paintball Hunting', NULL, 500.0, 1, 'Foto & Video', 'Optica', NULL, 100.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Router MSI RadiX AXE6600, 5x LAN', NULL, 800.0, 1, 'Retea', 'Retea & Wi-Fi', NULL, 475.0, NULL, NULL, NOW(), NOW()),
  ('Rode Wireless GO II | Dual Wireless Mic System', NULL, 700.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Robot geamuri WINBOT mini 2 Window Cleaning Robot', NULL, 1000.0, 1, 'Electrocasnice', 'Electrocasnice', NULL, 650.0, NULL, NULL, NOW(), NOW()),
  ('Ring Stick Up Cam Plug-In (3rd-Gen)', NULL, 250.0, 1, 'Smart Home', 'Camere supraveghere', 'Ring', 150.0, NULL, NULL, NOW(), NOW()),
  ('Ring Stick Up Cam Battery Indoor/Outdoor White', NULL, 150.0, 3, 'Smart Home', 'Camere supraveghere', 'Ring', 125.0, NULL, NULL, NOW(), NOW()),
  ('Ring Intercom Audio', NULL, 100.0, 2, 'Auto & Moto', 'Auto & Moto', 'Ring', 75.0, NULL, NULL, NOW(), NOW()),
  ('ring doorbell', NULL, 200.0, 2, 'Smart Home', 'Camere supraveghere', 'Ring', 150.0, NULL, NULL, NOW(), NOW()),
  ('Ring Chime Pro (2nd Generation) Wireless Sonerie ușă Wi-Fi', NULL, 150.0, 1, 'Smart Home', 'Camere supraveghere', 'Ring', 100.0, NULL, NULL, NOW(), NOW()),
  ('ring battrey doorbeel', NULL, 250.0, 1, 'Diverse electronice', 'Gadgeturi', 'Ring', 150.0, NULL, NULL, NOW(), NOW()),
  ('Revitive Medic Circulation Booster 5603-5573AQ-UK', NULL, 700.0, 1, 'Sanatate', 'Dispozitive medicale', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Razer Universal Quick Charging Stand xbox', NULL, 50.0, 1, 'Gaming', 'Gaming', 'Razer', 50.0, NULL, NULL, NOW(), NOW()),
  ('Rapsodo Golf MLM1 Launch Monitor', NULL, 800.0, 1, 'Monitoare', 'Monitoare', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('Radial Clutch master cylinder brembo 16rcs corsa corta', NULL, 900.0, 1, 'Auto & Moto', 'Piese moto', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Pyle pda69bueu Stereo Amplifier with Bluetooth, 300W HiFi Sound, Metal Panel', NULL, 290.0, 1, 'Audio', 'Mixere & Interfete', NULL, 205.0, NULL, NULL, NOW(), NOW()),
  ('PULWTOP bd182c USB C Docking Station For iMac 24" M1/M3/M4', NULL, 250.0, 1, 'Periferice PC', 'Periferice', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Proiector Video EPSON EH-TW6250, 4k PRO UHD, wireless, Android TV, 2800 lumeni, 35.000:1', NULL, 3500.0, 1, 'TV & Proiectoare', 'Proiectoare', NULL, 2000.0, NULL, NULL, NOW(), NOW()),
  ('Proiector Video Epson EB-770FI Full HD Laser 16:9 4100lm 2500000 :1 Alb', NULL, 5000.0, 6, 'TV & Proiectoare', 'Proiectoare', NULL, 3833.33, NULL, NULL, NOW(), NOW()),
  ('Portofel Crypto Keystone 3 Pro - Hardware wallet', NULL, 450.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Polti PAEU0405 29.6 V Lithium-ion Battery', NULL, 150.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('podofo carpl;ay', NULL, 100.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Placa intins par ghd Hair Straighteners & Flat Irons', NULL, 650.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'GHD', 400.0, NULL, NULL, NOW(), NOW()),
  ('Placa de baza folosita buna functionala MSI B860M GAMING PLUS WIFI', NULL, 400.0, 1, 'Gaming', 'Gaming', NULL, 125.0, NULL, NULL, NOW(), NOW()),
  ('Periuta electrica Philips Sonicare 3100 HX367515 2 bucati control presiune timer Sugar Rose si Negru', NULL, 225.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 200.0, NULL, NULL, NOW(), NOW()),
  ('Periuta de dinti electrica PHILIPS Sonicare HX4034/22, 31000 miscari/min, 4 programe, 2 capate, cutie, negru', NULL, 125.0, 18, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 100.0, NULL, NULL, NOW(), NOW()),
  ('Periuță de dinți electrică Neagră Philips Sonicare DiamondClean 9000 + irigator bucal Philips 3000', NULL, 1000.0, 3, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 600.0, NULL, NULL, NOW(), NOW()),
  ('PDP RIFFMASTER Wireless Guitar Controller', NULL, 200.0, 1, 'Instrumente muzicale', 'Chitare & Efecte', NULL, 125.0, NULL, NULL, NOW(), NOW()),
  ('Panasonic LUMIX DC-G81 body impecabil ca nou fara urme (lipseste obiectiv din cutie)', NULL, 2000.0, 1, 'Foto & Video', 'Obiective', NULL, 1450.0, NULL, NULL, NOW(), NOW()),
  ('Oura Ring 5 Silver Marimea 13, Titan, Smart Ring pentru Monitorizarea Somnului si Sanatatii, Pulsometru, SpO₂, Bluetooth, Rezistent la Apa', NULL, 1300.0, 6, 'Monitoare', 'Monitoare', 'Ring', 1000.0, NULL, NULL, NOW(), NOW()),
  ('Oura Gen3 Heritage Connected Ring - Size 12,', NULL, 700.0, 1, 'Wearables', 'Smart Rings', 'Ring', 500.0, NULL, NULL, NOW(), NOW()),
  ('OttoAibox P3 Pro CarPlay AI Box', NULL, 500.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Ondulator Remington Ci9532, ceramic cu extract de perle', NULL, 50.0, 2, 'Ingrijire personala', 'Ingrijire personala', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Öhlins line Sd 008 Universal Steering Damper 34.5-231.5 mm / 68 mm', NULL, 1400.0, 1, 'Auto & Moto', 'Piese moto', 'Ring', 600.0, NULL, NULL, NOW(), NOW()),
  ('Obiectiv Viltrox Cadru complet Obiectiv Foto AF 20mm f/2.8 Unghi larg pentru Montura Magazin online Sony E', NULL, 650.0, 1, 'Foto & Video', 'Obiective', 'Sony', 450.0, NULL, NULL, NOW(), NOW()),
  ('Obiectiv Sigma 90mm Obiectiv Foto Mirrorless F2.8 Contemporary DG DN Montura Sony FE', NULL, 2000.0, 1, 'Foto & Video', 'Obiective', 'Sony', 1300.0, NULL, NULL, NOW(), NOW()),
  ('Obiectiv Foto Mirrorless Sigma 45mm F2.8 DG HSM Contemporary Montura Sony FE', NULL, 1800.0, 1, 'Foto & Video', 'Obiective', 'Sony', 1000.0, NULL, NULL, NOW(), NOW()),
  ('Obiectiv Foto Mirrorless Nikon Z 26mm F2.8 Pancake', NULL, 1700.0, 1, 'Foto & Video', 'Obiective', 'Nikon', 1300.0, NULL, NULL, NOW(), NOW()),
  ('Obiectiv Benoison 85mm f1.8 Portrait Lens - E Mount Lens for Sony, Medium Telephoto Lenses (Manual Focus) for Sony A7C A7R A7S A7 A9 A6700 A6600 A6500 A6400 A6300 A6100 A6000 A5100 A5000 NEX-7 NEX-6 NEX-5 ZV-E10 etc', NULL, 300.0, 1, 'Foto & Video', 'Obiective', 'Sony', 225.0, NULL, NULL, NOW(), NOW()),
  ('Obiectiv AutoFocus Viltrox 85mm F1.4 Pro – Full Frame', NULL, 2400.0, 1, 'Foto & Video', 'Obiective', 'Viltrox', 1650.0, NULL, NULL, NOW(), NOW()),
  ('Norddampf RELICT Herb Vaporizer, Premium Vaporiser for Herbs, DHS & Intelisense Technology, 2600 mAh Battery, Insulated Airflow, Many Sessions, 30s Heating Time, Nordic Blue, No Nicotine', NULL, 250.0, 43, 'Diverse electronice', 'Vaping', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('night vision binoculars', NULL, 150.0, 1, 'Foto & Video', 'Optica', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('NEEWER NL-116AI Bi-Color 9" LED Video Panel Light', NULL, 150.0, 5, 'Foto & Video', 'Accesorii foto-video', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Navigatie Tomtom GO BASIC 6inch , navigation system (, Europe, WiFi, Bluetooth)', NULL, 300.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('navigatie smart sixwin', NULL, 250.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('navigatie navifly', NULL, 250.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Navigatie LAMTTO Wireless Apple Carplay & Android Auto for Car Stereo, Portable 7 inch Apple Car Play Touch Screen Sync GPS Navigation Audio Car Radio Receiver', NULL, 200.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Apple', 200.0, NULL, NULL, NOW(), NOW()),
  ('Navigatie auto Android ATOTO A6 Performance, 32GB ROM, 2GB RAM, Ecran 7" IPS Touchscreen, Apple CarPlay & Android Auto, MirrorLink, GPS, Bluetooth, USB, Radio FM, Wi-Fi, Functie camera marsarier live, Rama de instalare, Negru a6g2c7pf-s01', NULL, 800.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Apple', 450.0, NULL, NULL, NOW(), NOW()),
  ('navigatie android fiat 500 2gb/32gb', NULL, 350.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Mouse Turtle Beach Kone Ii, Cu Fir, Negru', NULL, 125.0, 5, 'Periferice PC', 'Periferice', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Mouse Samsung Slim EJ-M3400DSEGWW', NULL, 75.0, 4, 'Periferice PC', 'Periferice', 'Samsung', 62.5, NULL, NULL, NOW(), NOW()),
  ('Mouse Gaming ZOWIE EC2-DW 4K, Wireless, Negru', NULL, 400.0, 1, 'Gaming', 'Gaming', NULL, 250.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Mouse Gaming Glorious O 2 Mini, RGB, Wired, USB Alb', NULL, 125.0, 1, 'Gaming', 'Gaming', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Mouse Bluetooth APPLE Magic Mouse USB-C', NULL, 250.0, 1, 'Periferice PC', 'Periferice', 'Apple', 200.0, NULL, NULL, NOW(), NOW()),
  ('Monitor Video Pentru Bebelusi Maxi-Cosi See Pro, Cry Assistant, Ecran LCD de 5”, Ultra HD, Alb', NULL, 500.0, 22, 'Monitoare', 'Monitoare', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Monitor portabil Monitor de pantalla táctil de 13.3", HDMI+VGA FHD 1920x1080 IPS HDR 100% sRGB 60Hz pantalla táctil de 10 puntos con altavoces y VESA para portátil/Mini PC/PC Stick/TV Box/consolas de juegos', NULL, 250.0, 1, 'Sisteme PC', 'Mini PC', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Monitor portabil LED IPS Arzopa A1s 14", Full HD (1920x1080), 60Hz, Mini HDMI, USB-C, Boxe 1W x2', NULL, 150.0, 1, 'Monitoare', 'Monitoare', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('monitor portabil 18.5 129hz', NULL, 350.0, 1, 'Monitoare', 'Monitoare', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('monitor portabil', NULL, 250.0, 2, 'Monitoare', 'Monitoare', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('monitor panda touch digtreetech display', NULL, 150.0, 1, 'Monitoare', 'Monitoare', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Monitor dslr 5.5 Inch Touch Screen 1200nits Brightness Aluminum Housing DSLR Camera', NULL, 600.0, 1, 'Monitoare', 'Monitoare', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Mixer Maonocaster G1 NEO Audio Mixer & Interface', NULL, 125.0, 1, 'Audio', 'Mixere & Interfete', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Mixer audio BOMGE 06S 6 canale, Bluetooth, 99 efecte DSP, inregistrare stereo, portabil, 48V phantom, XLR out, Inerface audio, Placa de sunet, Potrivit pentru petreceri profesionale de inregistrare, KTV DJ si scena', NULL, 300.0, 1, 'Audio', 'Mixere & Interfete', NULL, 175.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC Origimagic C4, Ryzen 5 3550H, 16GB DDR4, 512GB SSD, suport 3 ecrane 4K, Wi-Fi 5, Windows 11 Pro', NULL, 1000.0, 1, 'Sisteme PC', 'Mini PC', NULL, 600.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC NiPoGi Pinova P1 AMD Ryzen 4300U W-11 Pro 8GB DDR4 RAM + 256GB SSD,', NULL, 600.0, 1, 'Sisteme PC', 'Mini PC', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC NiPoGi E3B, АMD Ryzen 5 7430U(Bis zu 4,3GHz) 512GB M.2 SSD Fara ram', NULL, 1000.0, 1, 'Sisteme PC', 'Mini PC', NULL, 1000.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC KAMRUI Pinova P1, AMD Ryzen 4300U, 16GB RAM 256GB SSD', NULL, 800.0, 1, 'Sisteme PC', 'Mini PC', NULL, 600.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC GEEKOM A5 Ryzen 7 5825U 16GB RAM 512GB + Win11 Pro', NULL, 1500.0, 1, 'Sisteme PC', 'Mini PC', NULL, 1000.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC Gaming AM06PRO, AMD Ryzen 5 5500U up to 4.0 GHz, 16 GB RAM, 512 GB SSD, Windows 11, Dual LAN RJ45, WiFi 5, BT 4.2, 4K Triple Display', NULL, 1000.0, 1, 'Sisteme PC', 'Mini PC', NULL, 650.0, NULL, NULL, NOW(), NOW()),
  ('Mini PC DreamQuest max Windows 11 Pro AMD Ryzen 5 7430U (up to 4.3 GHz), 16GB RAM & 512GB SSD (Both Upgradeable) Dual HDMI 4K, WiFi 6', NULL, 1100.0, 1, 'Sisteme PC', 'Mini PC', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Microfon XVive U3 Microphone Wireless System', NULL, 700.0, 1, 'Audio', 'Microfoane', 'XVive', 450.0, NULL, NULL, NOW(), NOW()),
  ('Microfon Studio Akg C 214', NULL, 1500.0, 1, 'Audio', 'Microfoane', NULL, 950.0, NULL, NULL, NOW(), NOW()),
  ('Lightech R Version adjustable rearsets Aprilia RS660 2020-2024 FTRAP007R', NULL, 2800.0, 2, 'Auto & Moto', 'Piese moto', NULL, 1300.0, NULL, NULL, NOW(), NOW()),
  ('LighTech Kawasaki ZX10R 2021> \'R\' Version Adjustable Rearsets FTRKA011R', NULL, 2200.0, 2, 'Auto & Moto', 'Piese moto', NULL, 1000.0, NULL, NULL, NOW(), NOW()),
  ('Lekato Guitar AMP ja-05G', NULL, 50.0, 2, 'Instrumente muzicale', 'Chitare & Efecte', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Lavaliera Neewer CM28 Wireless Lavalier Microphone System with Charging Case Noise Canceling', NULL, 300.0, 1, 'Audio', 'Microfoane', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('laptop Microsoft Surface laptop 13, 1st edition 13inch touchscreen, 16gb, 256gb , windows 11 - qwerty italia', NULL, 2300.0, 4, 'Laptopuri', 'Laptopuri', 'Microsoft', 1437.5, NULL, NULL, NOW(), NOW()),
  ('Laptop HP OmniBook 5 Flip x360 14-fp0001sl Convertible, Intel Core i3 1315U, 8GB RAM, 512GB SSD, 14" 2K Touch IPS Display, Intel UHD Graphics, PrivacyCam TNR 1080p, Windows 11, Silver', NULL, 1500.0, 1, 'Laptopuri', 'Laptopuri', 'HP', 1000.0, NULL, NULL, NOW(), NOW()),
  ('Laptop folosit Apple MacBook Air 13, Procesor Apple M5 chip (10-core CPU, 10-core GPU), 13.6" WQXGA, 16GB, 1TB, Martie 2026  hxq59c994d', NULL, 5000.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 3750.0, NULL, NULL, NOW(), NOW()),
  ('laptop Dell XPS 14 (Dell 14 Premium) DA14250 , 14,5inch FHD+ 1920 x 1200 IPS 30-120Hz, Procesor Ultra 7 255H, 32GB LPDDR5X, 1TB SSD, GeForce RTX 4050 6GB, Win 11 Pro, Platinum', NULL, 8500.0, 1, 'Laptopuri', 'Laptopuri', 'Dell', 6300.0, NULL, NULL, NOW(), NOW()),
  ('laptop Dell Pro Rugged 12 Tablet RA02260 ultar 5 236v, 16gb ddr5 8533mhz, 512gb, intel arc 130v', NULL, 8500.0, 2, 'Tablete', 'Tablete', 'Dell', 3000.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Dell Inspiron 5441 14.0\' FHD+, Snapdragon X Plus X1P-64-100, 16GB Ram, 512GB SSD, Adreno GPU, Windows 11 Pro', NULL, 2200.0, 1, 'Laptopuri', 'Laptopuri', 'Dell', 1700.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Apple MacBook Neo 13", 8GB, 256GB, Indigo, 13inch', NULL, 2400.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 2100.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Apple MacBook Neo 13" Retina cu procesor Apple A18 Pro 6 nuclee CPU, 5 nuclee GPU, 16 nuclee NeuralEngine, 8GB RAM, 512GB SSD S/m:kgl429xpqq  - 2jul2027 1 ciclu activat', NULL, 2800.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 1900.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Apple MacBook Neo 13" Apple A18 Pro, 6 nuclee CPU, 5 nuclee GPU, 16 nuclee Neural Engine, 8GB RAM, 256GB SSD', NULL, 2500.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 2100.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Apple MacBook Air 15\'\' M5, 10 nuclee CPU, 10 nuclee GPU, 16GB RAM, 512GB SSD, Midnight', NULL, 5500.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 4700.0, NULL, NULL, NOW(), NOW()),
  ('Laptop APPLE MacBook Air 13 M5 10-core CPU, 13.6" Retina Display, 16GB, SSD 512GB, 8-core GPU, macOS Sequoia, Sky Blue,', NULL, 5300.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 4500.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Apple MacBook Air 13\'\' Apple M5, 10 nuclee CPU, 10 nuclee GPU, 24GB RAM, 1TB SSD', NULL, 7000.0, 1, 'Laptopuri', 'Laptopuri', 'Apple', 5600.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Alienware Area-51 AA18250, 18inch WQXGA 300Hz, Procesor Ultra 9 275HX, 64GB DDR5, 2TB SSD, GeForce RTX 5090 24GB, Win 11 Pro', NULL, 22000.0, 1, 'Laptopuri', 'Laptopuri', NULL, 15000.0, NULL, NULL, NOW(), NOW()),
  ('Laptop Acer Chromebook 315 CB315-8H', NULL, 500.0, 1, 'Tablete', 'E-readere', 'Acer', 500.0, NULL, NULL, NOW(), NOW()),
  ('Lanterna Wurkkos HD05 Flat EDC Flashlight, 3100 Lumens 4 in 1 LED Rechargeable Torch with UV Red Light and Foldable Rotatable Side Light, USB-C High Lumens, IPX6 for Camping, Outdoor, Work', NULL, 150.0, 1, 'Accesorii', 'Lanterne', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Lanterna far bicicleta sau trotineta Olight RN800', NULL, 150.0, 1, 'Mobilitate electrica', 'Trotinete', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Lanterna bicicleta spate Olight Rn 120 C Bike Tail Lights, 120 Lumens And 260 Degree Visibility, 1500M Viewable Range, Rechargeable Bicycle Break Sensing', NULL, 200.0, 1, 'Mobilitate electrica', 'Biciclete electrice', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Kit Vaporesso Armour Ultra Obsidian', NULL, 100.0, 1, 'Diverse electronice', 'Vaping', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Kit Starter FIBARO Z-Wave Plus EU Cap Termostatic si Senzor de Temperatura Alb 5902701701079', NULL, 200.0, 3, 'Smart Home', 'Smart Home', 'Fibaro', 100.0, NULL, NULL, NOW(), NOW()),
  ('Kit motorizat Tilta Mirage VND MB-T16-B pentru accesorii de cameră', NULL, 1500.0, 1, 'Auto & Moto', 'Auto & Moto', NULL, 750.0, NULL, NULL, NOW(), NOW()),
  ('Kit Baby Monitor Babysense HD S2 cu 2 camere Audio-Video wireless pentru supraveghere Bebe, Ecran HD 5" LCD, Functie ecran divizat, Senzor Sunet, Zoom 4X, Mod Vedere Nocturna, Talk-Back, Lumina de veghe, Alb', NULL, 400.0, 7, 'Monitoare', 'Monitoare', NULL, 125.0, NULL, NULL, NOW(), NOW()),
  ('Joc nintendo Just Dance 2026 (Cod) pentru Nintendo Switch', NULL, 100.0, 15, 'Gaming', 'Gaming', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Jante Mercedes GT43 AMG 20 in 2 dimeniunsi - NOI!', NULL, 6500.0, 1, 'Auto & Moto', 'Piese moto', NULL, 5000.0, NULL, NULL, NOW(), NOW()),
  ('Inverter Victron Energy Blue Smart IP22 Inverter 24V Cu o singură fază BPC241647002', NULL, 600.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Interfata Audio Mixer Tc Helicon GoXLR Mini White', NULL, 450.0, 1, 'Audio', 'Mixere & Interfete', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Intercon moto ASMAX S1 Motorcycle Intercom Dual pack', NULL, 300.0, 1, 'Auto & Moto', 'Auto & Moto', NULL, 250.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Intercom Moto Bluetooth SENA 60S Wave Dual Pack Negru/Gri', NULL, 1200.0, 1, 'Auto & Moto', 'Auto & Moto', 'Sena', 800.0, NULL, NULL, NOW(), NOW()),
  ('Incuietoare inteligenta Aqara U200 Lite, neagra, wireless, compatibila Matter', NULL, 300.0, 1, 'Smart Home', 'Smart Home', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Încărcător multivoltaj XR de 8 A cu 4 porturi Dewalt DCB104-QW', NULL, 500.0, 1, 'Accesorii', 'Incarcatoare', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Incarcator Einhell PXC Power-X Twincharger, curent iesire 3A', NULL, 100.0, 1, 'Accesorii', 'Incarcatoare', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Incarcator Belkin BoostCharge Pro 3 in 1 Qi2 Wireless Charger, MagSafe Compatible Charger, Inductive Charging Station for Apple iPhone 17, Air, 16, Pixelsnap, Apple Watch, AirPods with Power Supply - White', NULL, 200.0, 11, 'Wearables', 'Smartwatch & Ceasuri', 'Apple', 150.0, NULL, NULL, NOW(), NOW()),
  ('Incarcator Belkin BoostCharge 2 in 1 Wireless Charger with Qi2 15W MagSafe Charger for iPhone 16, 15, 14, 13, 12, Apple Watch, AirPods and Other Qi2 Devices, Power Supply Included, Sand Grey', NULL, 200.0, 34, 'Wearables', 'Smartwatch & Ceasuri', 'Apple', 150.0, NULL, NULL, NOW(), NOW()),
  ('Incarcator Apple USB-C Power Adapter - 140Wmw2m3zm/a', NULL, 300.0, 4, 'Accesorii', 'Incarcatoare', 'Apple', 250.0, NULL, NULL, NOW(), NOW()),
  ('Husa tastatura WIWU iPad Pro 13 inch Keyboard Case M4/M5 2024/2025 Magnetic Detachable 3 in 1 Bluetooth Case Keyboard Adjustable Stand 7 Colors Backlit Keys with Touchpad (Grey, iPad Pro 13"(M4/M5 2024/2025))', NULL, 100.0, 1, 'Tablete', 'Tablete', 'iPad', 100.0, NULL, NULL, NOW(), NOW()),
  ('Husa tableta Samsung EF-BX810 Outer Case for Galaxy Tab S9+ s10+', NULL, 200.0, 1, 'Tablete', 'Tablete', 'Samsung', 200.0, NULL, NULL, NOW(), NOW()),
  ('Husa Smart Folio pentru APPLE iPad Air 13" (M3)/iPad Air 13" (M2), MWK93ZM/A, Charcoal Gray mwk93zm/a', NULL, 350.0, 1, 'Tablete', 'Tablete', 'Apple', 200.0, NULL, NULL, NOW(), NOW()),
  ('Husa de protectie Samsung Book Cover Keyboard pentru Galaxy Tab S10 Ultra/S9 Ultra Slim,', NULL, 350.0, 1, 'Periferice PC', 'Periferice', 'Samsung', 250.0, NULL, NULL, NOW(), NOW()),
  ('Husa cu tastatura Samsung Book Cover Keyboard - AI Key, Galaxy Tab S10+ | S10+ 5G | S9+ | S9 FE+ | S9 FE+ 5G 8806095773872 ef-dx825', NULL, 500.0, 1, 'Periferice PC', 'Periferice', 'Samsung', 200.0, NULL, NULL, NOW(), NOW()),
  ('Husa cu tastatura Apple Magic Keyboard Folio pentru iPad de 10.9inch 10th generatie', NULL, 550.0, 1, 'Tablete', 'Tablete', 'Apple', 300.0, NULL, NULL, NOW(), NOW()),
  ('hotone pulze control bt midi foot con', NULL, 150.0, 1, 'Instrumente muzicale', 'Chitare & Efecte', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Hotone EC-2 Pulze Control Bluetooth MIDI controller 6959473908068', NULL, 150.0, 1, 'Instrumente muzicale', 'Chitare & Efecte', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('HDD Extern Seagate Game Drive pentru PS5/PS4, 5TB, USB 3.0, Alb', NULL, 700.0, 1, 'Stocare', 'Stocare & Memorie', 'Seagate', 500.0, NULL, NULL, NOW(), NOW()),
  ('HDD extern Seagate Expansion, 16TB, 3.5", USB 3.0, Negru', NULL, 1600.0, 1, 'Stocare', 'Stocare & Memorie', 'Seagate', 1050.0, NULL, NULL, NOW(), NOW()),
  ('HDD extern Seagate Expansion, 10TB, 3.5", USB 3.0, Negru', NULL, 1000.0, 1, 'Stocare', 'Stocare & Memorie', 'Seagate', 350.0, NULL, NULL, NOW(), NOW()),
  ('hd binoculars', NULL, 100.0, 1, 'Foto & Video', 'Optica', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('GPS TomTom GO Classic 6 2nd generation 1YF6.002.00 GPS', NULL, 400.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Gps TomTom GO 520 Wi-F', NULL, 350.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('GPS TomTom car sat nav GO Classic 2nd generation 5"', NULL, 400.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Gps ciclism Garmin Edge Explore 2', NULL, 750.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Garmin', 500.0, NULL, NULL, NOW(), NOW()),
  ('Garmin CamperCam 795 | Navigator de rulote cu GPS', NULL, 1400.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Garmin', 950.0, NULL, NULL, NOW(), NOW()),
  ('Garmin Approach G82, Portable Golf Launch Monitor 010-02943-00', NULL, 2000.0, 1, 'Monitoare', 'Monitoare', 'Garmin', 1800.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Telefon Samsung Galaxy A55, Dual SIM, 8GB, 128GB, 5G,  urme de uzura fara cutie', NULL, 500.0, 1, 'Telefoane', 'Telefoane', 'Samsung', 500.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Router wireless, ZTE MC888, 5G, 17GB/s, Alb', NULL, 450.0, 1, 'Retea', 'Retea & Wi-Fi', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Folosit placa vide nvidia GTX750 4gb', NULL, 75.0, 1, 'Componente PC', 'Componente', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Ochelari AR XREAL One Pro, Ecran Virtual 171", 1080p, 120Hz, Sunet Bose, 87g, L (IPD 66-75mm)', NULL, 2000.0, 1, 'Wearables', 'Ochelari smart / AR-VR', 'Xreal', 1500.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Obiectiv Sony 55-200mm', NULL, 250.0, 1, 'Foto & Video', 'Obiective', 'Sony', 200.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Obiectiv Foto Mirrorless Sigma 10-18mm F2.8 DC DN [C] Montura Sony E', NULL, 2600.0, 1, 'Foto & Video', 'Obiective', 'Sony', 1600.0, NULL, NULL, NOW(), NOW()),
  ('FOLOSIT nivela laser', NULL, 100.0, 1, 'Scule & Unelte', 'Scule', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Monitor video și audio pentru bebeluși huh baby monitor', NULL, 100.0, 1, 'Monitoare', 'Monitoare', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Folosit GPS portabil, Garmin, eTrex SE', NULL, 350.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Garmin', 250.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Folosit Canon EOS 5D Mark II body', NULL, 700.0, 1, 'Foto & Video', 'Aparate foto', 'Canon', 600.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Focusrite Scarlett 16i16 4th Gen Interfață audio USB', NULL, 1000.0, 1, 'Audio', 'Mixere & Interfete', NULL, 600.0, NULL, NULL, NOW(), NOW()),
  ('Folosit fitbit charge 6', NULL, 250.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Fitbit', 200.0, NULL, NULL, NOW(), NOW()),
  ('Folosit drona 22', NULL, 100.0, 1, 'Foto & Video', 'Drone', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Folosit DJI RS 5 Stabilizator Gimbal pe 3 Axe', NULL, 2000.0, 1, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 1400.0, NULL, NULL, NOW(), NOW()),
  ('Folosit DJI Ronin S3 Mini Stabilizator Gimbal 3 Axe', NULL, 750.0, 1, 'Foto & Video', 'Stabilizatoare / Gimbal', 'DJI', 500.0, NULL, NULL, NOW(), NOW()),
  ('Folosit DJI Osmo Action 4 Camera de Actiune 4K Standard Combo', NULL, 750.0, 1, 'Foto & Video', 'Camere de actiune', 'DJI', 500.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Controller Wireless Xbox One Elite Series 2', NULL, 350.0, 1, 'Gaming', 'Gaming', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Controller Wireless SCUF Nomad', NULL, 150.0, 1, 'Gaming', 'Gaming', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Folosit chocolate plus fba m008 chocolate', NULL, 100.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 30.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Ceas multisport COROS PACE 3 GPS Sport Watch White w/ Silicone Band', NULL, 650.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Casti BOSE QuietComfort Ultra Earbuds 2nd gen', NULL, 550.0, 1, 'Audio', 'Casti', 'Bose', 400.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Casti Apple AirPods Max 2 (2026), Blue', NULL, 1700.0, 1, 'Audio', 'Casti', 'Apple', 1300.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Canon EOS 5D Mark IV Aparat Foto DSLR 30.4MP CMOS Body DS126601 454038000862 - 400/500 cadre', NULL, 5000.0, 1, 'Foto & Video', 'Aparate foto', 'Canon', 3200.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Cameră de supraveghere Blink Outdoor Camera 2K+, wireless, rezoluție 2K, autonomie de până la 2 ani, cu Sync Module Core inclus, alb, livrare 7-9 zile', NULL, 250.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 200.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Camera de supraveghere Blink Outdoor 4, Wireless, Full HD 1080p, IP65, vedere nocturna IR, detectare miscare, audio bidirectional, autonomie baterie pana la 2 ani, modul Sync Core, kit montaj inclus', NULL, 200.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 150.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Folosit Bratara Google Fitbit Air - Premium Gadgets', NULL, 200.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Fitbit', 150.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Blink - Battery Doorbell 2K+ (Add-On)', NULL, 150.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 100.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Blink - Battery Doorbell  (Add-On)', NULL, 100.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 100.0, NULL, NULL, NOW(), NOW()),
  ('Folosit autovox', NULL, 100.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Apple Watch SE 3, GPS, 44 mm, Midnight Aluminium Case, Midnight Sport Band - M/L DM2WG4J957', NULL, 800.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Apple', 600.0, NULL, NULL, NOW(), NOW()),
  ('Folosit Adaptor ViewSonic ViewShare WPD-900 Wireless Screen Casting Kit WPD-900', NULL, 150.0, 1, 'Audio', 'Casti', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Flash VK750II TTL Camera Flash Speedlite with LCD Screen Compatible with Nikon D3500 D3400 D3300 D3200 D3100 D5600 D7100 D7200 D5300 D5500 D500 D850 D750 and Other DSLR Cameras with Standard Hot Shoe', NULL, 100.0, 1, 'Foto & Video', 'Accesorii foto-video', 'Nikon', 100.0, NULL, NULL, NOW(), NOW()),
  ('Flash Godox iM20 iFlash Blit Patina pentru Camerele Foto', NULL, 75.0, 1, 'Foto & Video', 'Accesorii foto-video', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Filtru obiectiv K f concept lens folter nano x', NULL, 100.0, 2, 'Foto & Video', 'Obiective', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Film Polaroid pentru Polaroid Go, 48 buc', NULL, 100.0, 1, 'Foto & Video', 'Aparate foto', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('EZVIZ CB8 Kit 2K Outdoor Battery Camera with Solar Panel', NULL, 250.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('eztatttoo', NULL, 200.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Eufy 2C Add On IP Cameră de Supraveghere Wi-Fi Full HD 1080p Rezistentă la apă', NULL, 250.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 175.0, NULL, NULL, NOW(), NOW()),
  ('Espressor automat Philips LatteGo Seria 5400 EP5447, 1.8l, 1500W, 15 bar, negru-argintiu', NULL, 1500.0, 6, 'Electrocasnice', 'Electrocasnice', 'Philips', 1100.0, NULL, NULL, NOW(), NOW()),
  ('Epilator IPL PHILIPS Lumea Seria 9000 BRI955/00, 450.000 de impulsuri, 3 accesorii, tehnologie SenseIQ, acumulator, alb-roz', NULL, 1000.0, 2, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 800.0, NULL, NULL, NOW(), NOW()),
  ('elecrow portable monitor 5inch', NULL, 100.0, 1, 'Monitoare', 'Monitoare', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('E-book Reader RAKUTEN KOBO Clara BW, 6 inch Comfort Light, IPX8, 16GB, Wireless, Black', NULL, 650.0, 1, 'Tablete', 'E-readere', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Dyson Supersonic Travel Uscător de păr, HD19, Ceramic Pink/Rose Gold', NULL, 1200.0, 1, 'Ingrijire personala', 'Ingrijire personala', NULL, 800.0, NULL, NULL, NOW(), NOW()),
  ('DVD-rw asus external 16x dvd rw turbo', NULL, 400.0, 1, 'Stocare', 'Stocare & Memorie', 'Asus', 300.0, NULL, NULL, NOW(), NOW()),
  ('Drona Toladrone TD12LCD Drone with LCD Screen Remote', NULL, 150.0, 1, 'Foto & Video', 'Drone', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Drona DJI Lito X1 Fly More Combo (DJI RC 2) activata noua', NULL, 2700.0, 1, 'Foto & Video', 'Drone', 'DJI', 1800.0, NULL, NULL, NOW(), NOW()),
  ('Donner DBM-50 Bluetooth Page Turner Pedal', NULL, 100.0, 2, 'Audio', 'Microfoane', 'Donner', 50.0, NULL, NULL, NOW(), NOW()),
  ('DJI RC-N3 Remote Controller', NULL, 400.0, 1, 'Gaming', 'Gaming', 'DJI', 300.0, NULL, NULL, NOW(), NOW()),
  ('DJI Osmo Pocket 3 Battery Handle', NULL, 300.0, 2, 'Foto & Video', 'Drone', 'DJI', 150.0, NULL, NULL, NOW(), NOW()),
  ('DJI Mic Mini, 2 microfoane, 1 receptor, USB tip C', NULL, 250.0, 2, 'Diverse electronice', 'Gadgeturi', 'DJI', 200.0, NULL, NULL, NOW(), NOW()),
  ('DJI MIC Mini, 1x microfon, 1x incarcator, Wireless, Omnidirectional, Microfon wireless', NULL, 125.0, 1, 'Audio', 'Microfoane', 'DJI', 75.0, NULL, NULL, NOW(), NOW()),
  ('Dispozitiv de ingrijire a pielii Age-R Booster Pro 6-în-1 , Medicube', NULL, 500.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Medicube', 300.0, NULL, NULL, NOW(), NOW()),
  ('Digitnow digital film scanner', NULL, 200.0, 2, 'Foto & Video', 'Accesorii foto-video', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('DIGITNOW 4K HDMI USB 3.0 Capture Adapter', NULL, 125.0, 1, 'Accesorii', 'Cabluri & Adaptoare', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Digital delay Joyo D-SEED Digital Delay SET Efect de chitară', NULL, 250.0, 1, 'Instrumente muzicale', 'Chitare & Efecte', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Detector Semnal TV Satelit, Satfinder Profesional, SatLink™ ST-5150, Negru, DVB-S2, DVB-T2, DVB-C', NULL, 500.0, 1, 'TV & Proiectoare', 'Televizoare', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Detector fum x-sense XS0B-MR Smart Smoke Detector with Voice Alarm', NULL, 100.0, 1, 'Smart Home', 'Smart Home', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Cooler procesor Corsair iCUE LINK TITAN 240 RX RGB AIO, 240 mm, racire cu lichid, negru', NULL, 550.0, 1, 'Componente PC', 'Componente', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Controller xbox GameSir G7 Pro Tri-Mode Xbox & PC Controller', NULL, 250.0, 1, 'Gaming', 'Gaming', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Controller Turtle Beach Victrix Pro Bfg Reloaded Ps5/pc Wireless Controller', NULL, 400.0, 2, 'Gaming', 'Gaming', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Controller nintendo switch pro', NULL, 100.0, 1, 'Gaming', 'Gaming', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Controller cu fir GameSir G7 SE pentru Xbox Series X/S, Xbox One, PC', NULL, 65.0, 1, 'Gaming', 'Gaming', NULL, 5.0, NULL, NULL, NOW(), NOW()),
  ('Controller Controler fără fir 8BitDo - Ultimate 2 Wireless 2.4G, yellow nintendo switch/PC)', NULL, 150.0, 1, 'Gaming', 'Gaming', '8bitdo', 75.0, NULL, NULL, NOW(), NOW()),
  ('Controller 8bitdo Ultimate 3-mode White', NULL, 125.0, 1, 'Gaming', 'Gaming', '8bitdo', 100.0, NULL, NULL, NOW(), NOW()),
  ('Controler wireless Turtle Beach Rematch Nintendo Donkey Kong, design unic, autonomie 40 ore, multicolor', NULL, 100.0, 5, 'Gaming', 'Gaming', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Controler de joc Backbone One PlayStation Edition pentru USB-C', NULL, 300.0, 1, 'Gaming', 'Gaming', NULL, 125.0, NULL, NULL, NOW(), NOW()),
  ('Computer Moto m8 6.25 inch motorycle 6.25 Inch Motorcycle CarPlay Waterproof 800nit External Motorcycle Screen Support CarPlay and Android Auto Wireless Phone Link', NULL, 350.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Colorimetru Calibrite Display Pro HL Colorimetru', NULL, 800.0, 1, 'Foto & Video', 'Accesorii foto-video', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Cititor eBook Onyx Boox GO 7, ecran HD ePaper 7", 4GB RAM, 64GB', NULL, 800.0, 1, 'Tablete', 'E-readere', NULL, 550.0, NULL, NULL, NOW(), NOW()),
  ('CheckmeO2 Max Wrist Oximeter', NULL, 250.0, 1, 'Sanatate', 'Dispozitive medicale', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Centura puls Garmin HRM-Fit pentru femei 010-13314-00', NULL, 500.0, 1, 'Sanatate', 'Dispozitive medicale', 'Garmin', 300.0, NULL, NULL, NOW(), NOW()),
  ('Ceas smartwatch Amazfit Watch GTR 4, Black', NULL, 250.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Amazfit', 250.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Seiko Quartz SUR553P1', NULL, 600.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 550.0, NULL, NULL, NOW(), NOW()),
  ('Ceas orient RA-AP0003S30B', NULL, 600.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('ceas orient RA-AG0003S', NULL, 700.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 500.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Ceas de dama Citizen EP6050-17E Eco-Drive Promaster, 34mm, Argintiu', NULL, 500.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Citizen', 450.0, NULL, NULL, NOW(), NOW()),
  ('Ceas clasic invicta 46842 asin: 0886678620753', NULL, 300.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Citizen Watch Automatic Stainless NJ0151-88X', NULL, 700.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Citizen', 400.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Citizen Promaster Marine Diver Automatik NY0084-89EC', NULL, 750.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Citizen', 550.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Citizen Eco-Drive Gent AT2141-52L Clasic barbatesc', NULL, 1000.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Citizen', 700.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Citizen Eco-Drive CA4420-21X', NULL, 550.0, 1, 'Wearables', 'Smartwatch & Ceasuri', 'Citizen', 400.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Bulova Computron Silver Blue Dial Archive Series Watch 96c139 asin: 7613077569573', NULL, 700.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Ceas Bauhaus 2132-2 Dial With Date Wristwatch', NULL, 750.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Ceas barbatesc Timex Marlin Chronograph TW2w89700 0q', NULL, 800.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 550.0, NULL, NULL, NOW(), NOW()),
  ('Ceas barbatesc SEIKO SSB377p1', NULL, 600.0, 1, 'Wearables', 'Smartwatch & Ceasuri', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Casti wireless open ear Suunto Sonic', NULL, 150.0, 2, 'Audio', 'Casti', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Casti wireless Jabra Elite 3 Active, Jabra, Compatibilitate universala, Negru', NULL, 200.0, 1, 'Audio', 'Casti', 'Jabra', 150.0, NULL, NULL, NOW(), NOW()),
  ('Casti Uvex aXess one Bluetooth active, ascultare activa reala', NULL, 350.0, 1, 'Audio', 'Casti', 'Uvex', 250.0, NULL, NULL, NOW(), NOW()),
  ('Casti True Wireless Anker Soundcore Sleep A30 ANC, Ultra-Confort, Autonomie 45 ore', NULL, 450.0, 1, 'Audio', 'Casti', 'Anker', 300.0, NULL, NULL, NOW(), NOW()),
  ('Casti True Wireless Anker Soundcore Liberty Buds, Semi in-Ear, ANC, Autonomie 30 de ore', NULL, 125.0, 1, 'Audio', 'Casti', 'Anker', 100.0, NULL, NULL, NOW(), NOW()),
  ('Casti True Wireless Anker SoundCore C50i, Open Ear Clip-On, Hi-Res, IP55, Bluetooth 6.0, Autonomie 7/28 ore (Alb)', NULL, 100.0, 1, 'Audio', 'Casti', 'Anker', 75.0, NULL, NULL, NOW(), NOW()),
  ('Casti SKULLCANDY Crusher ANC 2 S6CAW-R740, Bluetooth, Over-Ear, Microfon, Noise Cancelling, True', NULL, 500.0, 1, 'Audio', 'Casti', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Casti Shokz OpenSwim Pro Black wireless bone conduction', NULL, 500.0, 2, 'Audio', 'Casti', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Casti Shokz OpenFit Pro Open Earbuds', NULL, 700.0, 1, 'Audio', 'Casti', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Casti Sennheiser Momentum Sport, Bluetooth, HR Monitor, Body Temp, Microfon,', NULL, 400.0, 1, 'Monitoare', 'Monitoare', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Casti Sennheiser IE 100 PRO In-Ear Monitoring Headphones (Clear)', NULL, 250.0, 1, 'Monitoare', 'Monitoare', 'Ring', 0.0, NULL, NULL, NOW(), NOW()),
  ('Casti profesionale de studio AKG K240 MKII', NULL, 200.0, 1, 'Audio', 'Casti', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Casti PC Turtle Beach Stealth Pro, Bluetooth, Negru, fara fir, cu microfon', NULL, 850.0, 2, 'Audio', 'Casti', NULL, 650.0, NULL, NULL, NOW(), NOW()),
  ('Casti Open-Ear Baseus Inspire XC1, Hybrid ANC, True wireless, Bluetooth 6.1, Dolby Audio & Hi-Res, Bluetooth 6.0, Autonimie 40h, IP66, Cosmic', NULL, 250.0, 1, 'Audio', 'Casti', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Căști Nothing Ear', NULL, 150.0, 1, 'Audio', 'Casti', 'Nothing', 150.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear Sennheiser Momentum True Wireless 4, Bluetooth, Microfon, Copper', NULL, 550.0, 1, 'Audio', 'Casti', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear Sennheiser Accentum Open TW, True Wireless, Bluetooth, Microfon, Autonomie 28 ore, IPX4,', NULL, 175.0, 20, 'Audio', 'Casti', NULL, 135.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear PHILIPS TAT6000BK/00, True Wireless, Bluetooth, 4 Microfoane, Hybrid ANC, Autonomie 28 ore, IPX5, Negru', NULL, 125.0, 7, 'Audio', 'Casti', 'Philips', 100.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear LINSOUL Kiwi Ears Astral, Hibride 1Dd+6Ba', NULL, 1000.0, 1, 'Audio', 'Casti', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear Huawei FreeBuds 6i, True Wireless, Hybrid ANC, Bluetooth, Black', NULL, 150.0, 1, 'Audio', 'Casti', 'Huawei', 100.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear CMF Buds Pro 2 by Nothing', NULL, 125.0, 1, 'Audio', 'Casti', 'Nothing', 100.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear Beyerdynamic Amiron 300, True Wireless, Bluetooth, Multipoint, ANC, Autonomie 38 ore, Black', NULL, 500.0, 1, 'Audio', 'Casti', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Casti In-Ear Anker SoundCore Sleep A30, True Wireless, Smart ANC (Snore Masking System), Bluetooth 5.4, Autonomie 45H, IPX4, Verde', NULL, 500.0, 1, 'Audio', 'Casti', 'Anker', 300.0, NULL, NULL, NOW(), NOW()),
  ('Casti Gaming Wireless STEELSERIES Arctis Nova 5P Wireless, Spatial Audio, multiplatforma, negru', NULL, 250.0, 1, 'Audio', 'Casti', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Casti gaming Turtle Beach Recon 70, multiplatforma, 3.5mm jack, Camo Blue', NULL, 50.0, 5, 'Audio', 'Casti', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOWERS & WILKINS Px8, Bluetooth, Over-Ear, Microfon, Noise Cancelling,', NULL, 1300.0, 1, 'Audio', 'Casti', 'Bowers & Wilkins', 900.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOWERS & WILKINS Px7 S2e, Bluetooth, Over-Ear, Microfon, Noise Cancelling', NULL, 700.0, 2, 'Audio', 'Casti', 'Bowers & Wilkins', 500.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOSE Ultra Open Earbuds, True Wireless, Bluetooth, Open-ear, Microfon,', NULL, 600.0, 13, 'Audio', 'Casti', 'Bose', 450.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOSE QuietComfort Ultra Headphones 2nd Gen, Bluetooth, Over-Ear, Microfon, Noise Cancelling,', NULL, 1300.0, 1, 'Audio', 'Casti', 'Bose', 1000.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOSE QuietComfort Ultra Earbuds, True Wireless, Bluetooth, In-Ear, Microfon, Noise Cancelling,', NULL, 570.0, 1, 'Audio', 'Casti', 'Bose', 500.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOSE QuietComfort Ultra Earbuds 2nd Gen, True Wireless, Bluetooth, In-Ear, Microfon, Noise Cancelling, Black', NULL, 720.0, 2, 'Audio', 'Casti', 'Bose', 625.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOSE QuietComfort Headphones, Bluetooth, Over-Ear, Microfon, Noise Cancelling, Black', NULL, 600.0, 2, 'Audio', 'Casti', 'Bose', 450.0, NULL, NULL, NOW(), NOW()),
  ('Casti BOSE QuietComfort Earbuds, Bluetooth, In-Ear, Microfon, Noise Cancelling, White Smoke', NULL, 400.0, 2, 'Audio', 'Casti', 'Bose', 300.0, NULL, NULL, NOW(), NOW()),
  ('Casti Beyerdynamic Amiron 300 True Wireless Earphones', NULL, 950.0, 1, 'Audio', 'Casti', NULL, 630.0, NULL, NULL, NOW(), NOW()),
  ('Casti BEATS Solo 4, Bluetooth, On-ear, Microfon, Noise Cancelling', NULL, 400.0, 1, 'Audio', 'Casti', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Casti BEATS Powerbeats Pro 2, True Wireless, Bluetooth, In-Ear, Microfon, Noise Cancelling, Heart Rate Monitoring, Jet Black', NULL, 600.0, 1, 'Monitoare', 'Monitoare', 'Ring', 500.0, NULL, NULL, NOW(), NOW()),
  ('Casti Audio Wireless In Ear Bose QuietComfort Earbuds, Bluetooth, ANC,IPX4, Black', NULL, 350.0, 1, 'Audio', 'Casti', 'Bose', 250.0, NULL, NULL, NOW(), NOW()),
  ('Casti audio waterproof Shokz OpenRun Pro 2-Portocaliu', NULL, 700.0, 1, 'Audio', 'Casti', NULL, 425.0, NULL, NULL, NOW(), NOW()),
  ('Casti audio telefon Sony WF-1000XM6', NULL, 800.0, 1, 'Audio', 'Casti', 'Sony', 700.0, NULL, NULL, NOW(), NOW()),
  ('Casti audio telefon Sony WF-1000XM5', NULL, 550.0, 4, 'Audio', 'Casti', 'Sony', 500.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Casti audio Shokz OpenFit Air', NULL, 250.0, 1, 'Audio', 'Casti', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Casti audio in-ear Jabra Elite 85t, True Wireless, Bluetooth, Titan', NULL, 450.0, 1, 'Audio', 'Casti', 'Jabra', 350.0, NULL, NULL, NOW(), NOW()),
  ('Casti Audio In Ear Bose QuietComfort Earbuds', NULL, 350.0, 1, 'Audio', 'Casti', 'Bose', 300.0, NULL, NULL, NOW(), NOW()),
  ('Casti audio in ear Beats Studio Buds+, True Wireless, Noise Cancelling', NULL, 550.0, 1, 'Audio', 'Casti', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Casti audio Anker SoundCore Liberty 4 Pro', NULL, 175.0, 2, 'Audio', 'Casti', 'Anker', 150.0, NULL, NULL, NOW(), NOW()),
  ('Casti Audio AKG K72 Over-Ear', NULL, 800.0, 1, 'Audio', 'Casti', NULL, 600.0, NULL, NULL, NOW(), NOW()),
  ('Casti APPLE EarPods MYQY3ZM/A, Cu Fir, In-ear, Microfon, USB-C, alb', NULL, 25.0, 1, 'Audio', 'Casti', 'Apple', 25.0, NULL, NULL, NOW(), NOW()),
  ('Casti alergare wireless Shokz OpenFit 2 Plus, autonomie 11-48 ore, Bluetooth 5.4, MultiPoint Pairing, IP55 (Negru)', NULL, 700.0, 6, 'Audio', 'Casti', 'Ring', 450.0, NULL, NULL, NOW(), NOW()),
  ('Casti alergare wireless Shokz OpenDots One, Bluetooth 5.4, Autonomie 10 ore, IP54', NULL, 700.0, 8, 'Audio', 'Casti', NULL, 450.0, NULL, NULL, NOW(), NOW()),
  ('Casca Jabra Evolve2 55, with charging station, headset (, mono, Microsoft Teams, USB-A, Link380a)', NULL, 350.0, 2, 'Audio', 'Casti', 'Jabra', 200.0, NULL, NULL, NOW(), NOW()),
  ('carpuride moto', NULL, 450.0, 1, 'Auto & Moto', 'Auto & Moto', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('carplay screen VOLOM 9 inch', NULL, 200.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Carestream Kodak Rvg 5200 Digital Radiography System - size 2', NULL, 5000.0, 2, 'Foto & Video', 'Aparate foto', 'Kodak', 1400.0, NULL, NULL, NOW(), NOW()),
  ('Carestream Kodak Rvg 5200 Digital Radiography System - size 1', NULL, 5000.0, 2, 'Foto & Video', 'Aparate foto', 'Kodak', 1400.0, NULL, NULL, NOW(), NOW()),
  ('Carestream CS 1500 Intraoral Camera (Wired)', NULL, 5000.0, 1, 'Foto & Video', 'Camere', NULL, 1400.0, NULL, NULL, NOW(), NOW()),
  ('Canon CanoScan LIDE 400 (CPX1889786)', NULL, 250.0, 1, 'Foto & Video', 'Accesorii foto-video', 'Canon', 200.0, NULL, NULL, NOW(), NOW()),
  ('Camera wolfang trail camera', NULL, 100.0, 1, 'Foto & Video', 'Camere de actiune', 'Wolfang', 75.0, NULL, NULL, NOW(), NOW()),
  ('Camera Wildlife XTU sv-32yw WiFi Bluetooth - 2.7K 48MP Trail Camera with Night Vision Motion Activated with 64GB Micro SD Card,IP66 Waterproof 120° Detection Angle 950nm No Glow LED for Hunting Garden (UK)', NULL, 150.0, 1, 'Foto & Video', 'Optica', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Camera Web LOGITECH MX Brio, 4K Ultra HD, grafit', NULL, 350.0, 1, 'Foto & Video', 'Camere', 'Logitech', 275.0, NULL, NULL, NOW(), NOW()),
  ('Camera videoconferinta wireless Logitech Rally Bar Mini, 4K, LAN, HDMI, USB, Graphite', NULL, 5000.0, 1, 'Foto & Video', 'Camere', 'Logitech', 4000.0, NULL, NULL, NOW(), NOW()),
  ('Camera video Web Insta360 Link 2C Standard Edition, Ultra HD 4K', NULL, 450.0, 29, 'Foto & Video', 'Camere', NULL, 285.71, NULL, NULL, NOW(), NOW()),
  ('Camera video sport DJI Osmo Action4 Standard Combo', NULL, 900.0, 1, 'Foto & Video', 'Camere de actiune', 'DJI', 650.0, NULL, NULL, NOW(), NOW()),
  ('Camera urmarit fauna WOLFANG Wildlife Camera, 48MP 4K Trail', NULL, 100.0, 1, 'Foto & Video', 'Camere de actiune', 'Wolfang', 75.0, NULL, NULL, NOW(), NOW()),
  ('Camera supraveghere WOLFANG Wildlife Camera 48MP 4K HD, Trail Camera with 940 nm IR LEDs, Hunting Camera with Night Vision Motion Activated, IP66 Waterproof, 0.3s Trigger Time for Wildlife Recording、Indoor Monitoring', NULL, 100.0, 1, 'Monitoare', 'Monitoare', 'Wolfang', 50.0, NULL, NULL, NOW(), NOW()),
  ('Camera supraveghere panoramica IP Reolink Duo 3 P750, 16 MP, IR / lumina alba 30 m, 2.8 mm, PoE, microfon, difuzor, slot card, detectie persoane / vehicule / animale', NULL, 600.0, 66, 'Audio', 'Boxe & Soundbar', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Camera supraveghere IP Hikvision acusense', NULL, 350.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Camera supraveghere eufy SoloCam E30, Wireless, 2K HD, Panou Solar, Supraveghere 360, 2.4 GHz Wi-Fi, IP65', NULL, 450.0, 3, 'Smart Home', 'Camere supraveghere', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Camera Supraveghere Camera de supraveghere TP-Link Tapo C615F KIT, solara, 3MP, IP65, audio, set', NULL, 350.0, 1, 'Smart Home', 'Camere supraveghere', 'TP-Link', 200.0, NULL, NULL, NOW(), NOW()),
  ('Camera supraveghere 4G si Wi-Fi EZVIZ CB8 Lite, 4MP, 4mm, AOV 2.0, detectie AI, audio bidirectional, panou solar, IP65, CS-CB8c/SP (4MP.W4GA)', NULL, 300.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Camera securitate INSTAR IN-9408 2K+ LAN/PoE', NULL, 900.0, 1, 'Foto & Video', 'Camere', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Camera securitate eufy SoloCam S220 (2-Cam Pack)', NULL, 600.0, 1, 'Foto & Video', 'Camere', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Camera securitate aosu T2 Pro 3K Outdoor Solar Surveillance Camera, 5MP Dual Camera, 360° PTZ + 170° Wide Angle, Auto Tracking, 8X Zoom, AI Detection for People/Vehicles/Pets, Real Full Colour Night Vision', NULL, 400.0, 1, 'Foto & Video', 'Optica', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Camera sec Ring Stick Up Cam IP Cameră de Supraveghere Wi-Fi Full HD 1080p Rezistentă la apă Pe baterii cu Comunicare Bidirecțională', NULL, 200.0, 1, 'Smart Home', 'Camere supraveghere', 'Ring', 150.0, NULL, NULL, NOW(), NOW()),
  ('Camera Puooifrty HC600A 1080P Solar Hunting Camera Video', NULL, 75.0, 1, 'Foto & Video', 'Camere', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Camera moto IXROAD Motorcycle Dash Cam with CarPlay and Android Auto', NULL, 450.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Ixroad', 300.0, NULL, NULL, NOW(), NOW()),
  ('Camera izeeker trail camera', NULL, 100.0, 1, 'Foto & Video', 'Camere de actiune', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Camera Foto Instant Polaroid Now Gen 3 Negru', NULL, 300.0, 1, 'Foto & Video', 'Aparate foto', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Camera Externa cu Termoviziune Topdon TC001 25 Hz, compatibila Android si Windows, USB-C', NULL, 800.0, 1, 'Foto & Video', 'Camere', NULL, 400.0, NULL, NULL, NOW(), NOW()),
  ('Camera de supraveghere wireless Blink Outdoor 4 (1pack)', NULL, 200.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 150.0, NULL, NULL, NOW(), NOW()),
  ('Camera de supraveghere Reolink RLC 811A cu inteligenta artificiala, detectare Persoana/Vehicul, zoom optic 5x, rezolutie de 8MP (4K)', NULL, 350.0, 32, 'Smart Home', 'Camere supraveghere', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Cameră De supraveghere Blink Outdoor 2k+ 2pack', NULL, 350.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 200.0, NULL, NULL, NOW(), NOW()),
  ('Camera de actiune DJI Osmo Pocket 3 Creator Combo, 4K, Wi-Fi, gri', NULL, 2000.0, 1, 'Foto & Video', 'Camere de actiune', 'DJI', 1200.0, NULL, NULL, NOW(), NOW()),
  ('Camera de Actiune Akaso EK7000 Pro 4K 16MP', NULL, 150.0, 1, 'Foto & Video', 'Camere de actiune', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Camera auto DVR Baseus PrimeTrip VD1 Pro 4K, Bluetooth, Wi-Fi, neagra, 64x63x38mm', NULL, 250.0, 1, 'Foto & Video', 'Camere', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Camera auto de bord Vantrue E1 Lite Mini, WiFi 1080P HDR/30fps, cu control vocal, Night Vision 160, ecran 1.54", GPS, G-sensor si monitorizare parcare', NULL, 250.0, 29, 'Monitoare', 'Monitoare', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Calculator grafic avansat Casio fx-CG50, 3.17” afisaj color, 2900, 3D-Graph, White/', NULL, 350.0, 3, 'Diverse electronice', 'Gadgeturi', NULL, 166.67, NULL, NULL, NOW(), NOW()),
  ('Buton control acces Nuki Opener, compatibil Nuki Smart Lock, bluetooth', NULL, 350.0, 1, 'Smart Home', 'Smart Home', 'Nuki', 100.0, NULL, NULL, NOW(), NOW()),
  ('BTICINO 344652Classe 100V16B Hands-free video internal unit USED like new', NULL, 600.0, 1, 'Smart Home', 'Smart Home', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('braun silk expret pro 5', NULL, 300.0, 1, 'Ingrijire personala', 'Ingrijire personala', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Bratara fitness Garmin Index Sleep Monitor S-M, 010-03024-01', NULL, 600.0, 7, 'Monitoare', 'Monitoare', 'Garmin', 350.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('Bratara fitness Fitbit Inspire 3 Midnight Zen/', NULL, 250.0, 2, 'Wearables', 'Smartwatch & Ceasuri', 'Fitbit', 200.0, NULL, NULL, NOW(), NOW()),
  ('Bratara fitness Fitbit Charge 6, GPS + GLONASS, Bluetooth, NFC, Negru', NULL, 400.0, 3, 'Auto & Moto', 'GPS & Navigatie', 'Fitbit', 300.0, NULL, NULL, NOW(), NOW()),
  ('Boxa Ultimate Ears EpicBoom, Bluetooth, NFC, alb', NULL, 1100.0, 1, 'Audio', 'Boxe & Soundbar', NULL, 700.0, NULL, NULL, NOW(), NOW()),
  ('Boxa portabila SONY BRAVIA Theatre U HT-AN7, Bluetooth, Dolby Atmos, IPX4, negru', NULL, 650.0, 2, 'Audio', 'Boxe & Soundbar', 'Sony', 412.5, NULL, NULL, NOW(), NOW()),
  ('Boxa Newline NewPie Bluetooth Speakerphone', NULL, 100.0, 1, 'Audio', 'Boxe & Soundbar', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Boxa Laney LX10B Small Bass Combo', NULL, 250.0, 1, 'Audio', 'Boxe & Soundbar', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Boxa Anker PowerConf+ Bluetooth & USB Speakerphone', NULL, 200.0, 1, 'Audio', 'Boxe & Soundbar', 'Anker', 150.0, NULL, NULL, NOW(), NOW()),
  ('bodycam with audio/video', NULL, 75.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Blu-ray Player Sony UBP-X700K', NULL, 800.0, 1, 'Audio', 'Audio Hi-Fi', 'Sony', 650.0, NULL, NULL, NOW(), NOW()),
  ('blink video doorbell', NULL, 200.0, 1, 'Smart Home', 'Camere supraveghere', 'Blink', 150.0, NULL, NULL, NOW(), NOW()),
  ('biomaser s20', NULL, 200.0, 1, 'Diverse electronice', 'Gadgeturi', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Biib led 1 pair', NULL, 5.0, 170, 'Diverse electronice', 'Gadgeturi', NULL, 4.1, NULL, NULL, NOW(), NOW()),
  ('belkin boostcharge pro magnetic wireless pad', NULL, 50.0, 6, 'Diverse electronice', 'Gadgeturi', 'Belkin', 25.0, NULL, NULL, NOW(), NOW()),
  ('Behringer DJX900USB mixer, DJ, 5 canale, INFINIUM VCA Crossfader, efecte digitale, interfață USB/Audio', NULL, 750.0, 3, 'Audio', 'Mixere & Interfete', 'Ring', 500.0, NULL, NULL, NOW(), NOW()),
  ('Baterie DJI Avata 360 Intelligent Flight Battery', NULL, 300.0, 2, 'Foto & Video', 'Drone', 'DJI', 175.0, NULL, NULL, NOW(), NOW()),
  ('Baseus S1 Lite Solar Security Cameras Wireless Outdoor , 2K QHD Solocam, Continuous Power, Color Night Vision, AI Human Detection, IP67, No Monthly Fee, Local Storage, Works with Alexa & Google Home', NULL, 150.0, 2, 'Foto & Video', 'Optica', 'Google', 100.0, NULL, NULL, NOW(), NOW()),
  ('bartesian premium cocktails on demand', NULL, 1000.0, 1, 'Electrocasnice', 'Electrocasnice', NULL, 1000.0, NULL, NULL, NOW(), NOW()),
  ('Barcode Scanner YANZEO SR290 UHF RFID Reader Handheld Terminal 1D/2D QR Barcode Reader Bluetooth 2.4 GHz+Wired USB Bar Code Reader for Jewelry/Clothing/Shoe Store, Supermarket, Warehouse', NULL, 500.0, 1, 'Foto & Video', 'Aparate foto', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('Banda monitorizare cardiaca, Polar Verity Sense, Bluetooth, Gri, marime ajustabila M-XXL', NULL, 275.0, 2, 'Monitoare', 'Monitoare', NULL, 150.0, NULL, NULL, NOW(), NOW()),
  ('baby monitor dr care dc-sbm005 dual', NULL, 500.0, 1, 'Monitoare', 'Monitoare', NULL, 350.0, NULL, NULL, NOW(), NOW()),
  ('Asustor Drivestor 2 Gen 2 AS1202T 2-Bay NAS Storage, Quad-Core 1.7GHz CPU, 2.5GbE High-Speed Network, 1GB DDR4, 4K Media Server, Best Entry-Level Personal Cloud, Network Attached Storage (Diskless)', NULL, 600.0, 1, 'Stocare', 'Stocare & Memorie', 'Asustor', 400.0, NULL, NULL, NOW(), NOW()),
  ('Aspirator robot Dreame - L40s Pro Ultra, HEPA, alb', NULL, 1800.0, 1, 'Electrocasnice', 'Electrocasnice', NULL, 1300.0, NULL, NULL, NOW(), NOW()),
  ('Arlo Essential Outdoor FHD (Gen 2) pack of 3', NULL, 700.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 375.0, NULL, NULL, NOW(), NOW()),
  ('Arlo Essential 2K Outdoor Security Camera 2nd gen', NULL, 300.0, 1, 'Smart Home', 'Camere supraveghere', NULL, 200.0, NULL, NULL, NOW(), NOW()),
  ('Apple Watch SE 3, GPS + Cellular, 44 mm, Midnight Aluminium Case, Midnight Sport Band - M/L', NULL, 1200.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Apple', 1000.0, NULL, NULL, NOW(), NOW()),
  ('Apple Watch 11 GPS + Cellular 46mm, Carcasa Space Grey Aluminium , Black Sport Band - S/M', NULL, 2000.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Apple', 1600.0, NULL, NULL, NOW(), NOW()),
  ('APPLE Pencil Pro pentru iPad Air 13/11 (M3/M2), iPad mini 7, iPad Pro 13/11 (M5/M4), MX2D3ZM/A, alb', NULL, 500.0, 6, 'Tablete', 'Tablete', 'Apple', 350.0, NULL, NULL, NOW(), NOW()),
  ('APPLE Pencil 1st Gen pentru iPad 11/10/9, iPad Air 3, iPad Pro 12.9, MQLY3ZM/A', NULL, 275.0, 2, 'Tablete', 'Tablete', 'Apple', 200.0, NULL, NULL, NOW(), NOW()),
  ('APPLE Pencil (USB-C) pentru iPad Pro, iPad Air, iPad 11/10, iPad Mini, MUWA3ZM/A, alb', NULL, 300.0, 6, 'Tablete', 'Tablete', 'Apple', 283.33, NULL, NULL, NOW(), NOW()),
  ('Apple Magic Trackpad 3, Multi-Touch Surface, Negru', NULL, 400.0, 1, 'Periferice PC', 'Periferice', 'Apple', 250.0, NULL, NULL, NOW(), NOW()),
  ('Apple Magic Trackpad 3, Multi-Touch Surface, Alb', NULL, 300.0, 3, 'Periferice PC', 'Periferice', 'Apple', 233.33, NULL, NULL, NOW(), NOW()),
  ('Apple Magic Mouse mxk53z/a', NULL, 250.0, 1, 'Periferice PC', 'Periferice', 'Apple', 200.0, NULL, NULL, NOW(), NOW()),
  ('APPLE Magic Keyboard pentru iPad Pro 11" (M5/M4), mwr23d/a QWERTZ', NULL, 800.0, 1, 'Tablete', 'Tablete', 'Apple', 650.0, NULL, NULL, NOW(), NOW()),
  ('Aparat tatuat peripage tattoo buetooth printer', NULL, 250.0, 1, 'Ingrijire personala', 'Aparate tatuat', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Aparat tatuat ez tattoo machine', NULL, 500.0, 1, 'Ingrijire personala', 'Aparate tatuat', NULL, 300.0, NULL, NULL, NOW(), NOW()),
  ('Aparat tatuat dragonhawk tattoo', NULL, 100.0, 1, 'Ingrijire personala', 'Aparate tatuat', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Aparat Foto Mirrorless Sony Alpha A6100 Kit cu Obiectiv E PZ 16-50mm F3.5-5.6 OSS II Negru', NULL, 2800.0, 1, 'Foto & Video', 'Obiective', 'Sony', 1750.0, NULL, NULL, NOW(), NOW()),
  ('Aparat foto Mirrorless Olympus E-M10 Mark IV', NULL, 2600.0, 1, 'Foto & Video', 'Aparate foto', NULL, 1800.0, NULL, NULL, NOW(), NOW()),
  ('Aparat Foto Mirrorless Fujifilm X-S20 Kit cu Obiectiv 15-45mm', NULL, 5000.0, 1, 'Foto & Video', 'Obiective', NULL, 3600.0, NULL, NULL, NOW(), NOW()),
  ('Aparat Foto Mirrorless Fujifilm X-M5 26MP 6K Kit cu Obiectiv XC 15-45mm Argintiu', NULL, 3300.0, 1, 'Foto & Video', 'Obiective', NULL, 2700.0, NULL, NULL, NOW(), NOW()),
  ('Aparat Foto KODAK PIXPRO C1 Retro', NULL, 300.0, 2, 'Foto & Video', 'Aparate foto', 'Kodak', 250.0, NULL, NULL, NOW(), NOW()),
  ('Aparat foto instant Polaroid Now (gen.3', NULL, 350.0, 1, 'Foto & Video', 'Aparate foto', NULL, 250.0, NULL, NULL, NOW(), NOW()),
  ('Aparat foto instant Fujifilm instax mini 13', NULL, 300.0, 1, 'Foto & Video', 'Aparate foto', NULL, 225.0, NULL, NULL, NOW(), NOW()),
  ('Aparat foto digital Kodak PIXPRO AZ425, zoom 42x, 20mp', NULL, 500.0, 1, 'Foto & Video', 'Aparate foto', 'Kodak', 500.0, NULL, NULL, NOW(), NOW()),
  ('Aparat foto digital Kodak Pixpro AZ405, negru', NULL, 700.0, 1, 'Foto & Video', 'Aparate foto', 'Kodak', 500.0, NULL, NULL, NOW(), NOW()),
  ('Aparat electric de barbierit PHILIPS Seria i9000 Pestige XP9207/30 - nou cutie desigilata', NULL, 650.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 400.0, NULL, NULL, NOW(), NOW()),
  ('Aparat electric de bărbierit (umed&uscat) cu SkinIQ Philips xp9207/39 8720689036795', NULL, 700.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 450.0, NULL, NULL, NOW(), NOW()),
  ('Aparat de sudura portabil Awithz P90C New Portable Welding Machine Adjustable LED Screen Spot Welder for Battery Metal Spot Welding', NULL, 1850.0, 6, 'Scule & Unelte', 'Scule', NULL, 850.0, NULL, NULL, NOW(), NOW()),
  ('Aparat de ras Philips x9001/30, x Model 8720689030038', NULL, 900.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 450.0, NULL, NULL, NOW(), NOW()),
  ('Aparat de ras Philips Seria 3000 S3244/12, Fara fir, Barbierit uscat si umed, Lame PowerCut, Autonomie 60 min, Gri inchis', NULL, 100.0, 1, 'Ingrijire personala', 'Ingrijire personala', 'Philips', 100.0, NULL, NULL, NOW(), NOW());

INSERT INTO products (name, description, price, stock_quantity, category, subcategory, brand, purchase_price, sku, image_url, created_at, updated_at) VALUES
  ('android tv telesystem up t2', NULL, 100.0, 1, 'TV & Proiectoare', 'Televizoare', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Amazon Fire HD 10 2023 13th Gen 32GB', NULL, 100.0, 1, 'Tablete', 'Tablete', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('AFFETUNI Digital Voice Recorder Z8 Voice Recorder', NULL, 100.0, 1, 'Audio', 'Microfoane', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('Adaptor ViewSonic ViewShare WPD-900 Wireless Screen Casting Kit WPD-900', NULL, 150.0, 1, 'Audio', 'Casti', NULL, 50.0, NULL, NULL, NOW(), NOW()),
  ('Acumulator WORX WA3551, 20V, 2.0Ah', NULL, 100.0, 1, 'Scule & Unelte', 'Scule', NULL, 75.0, NULL, NULL, NOW(), NOW()),
  ('Acumulator inteligent DJI Mini 3 Pro', NULL, 200.0, 1, 'Foto & Video', 'Drone', 'DJI', 150.0, NULL, NULL, NOW(), NOW()),
  ('Acumulator Extern Anker 25.000 mAh 165W 100W USB-C Cablu USB-C Retractabil Gri', NULL, 200.0, 1, 'Accesorii', 'Baterii externe', 'Anker', 150.0, NULL, NULL, NOW(), NOW()),
  ('acumulator anker', NULL, 150.0, 1, 'Accesorii', 'Baterii externe', 'Anker', 50.0, NULL, NULL, NOW(), NOW()),
  ('action camera wolfang', NULL, 100.0, 1, 'Foto & Video', 'Camere de actiune', 'Wolfang', 75.0, NULL, NULL, NOW(), NOW()),
  ('5 Inch Motorcycle Carplay GPS', NULL, 150.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('4g lte camera', NULL, 100.0, 1, 'Foto & Video', 'Camere', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('4 Port High Resolution USB DVI Dual Link KVM Switch with Audio - TAA', NULL, 1000.0, 1, 'Periferice PC', 'Periferice', NULL, 500.0, NULL, NULL, NOW(), NOW()),
  ('1Control 2ª GEN Wireless Bluetooth Gate Opener, Garage Door Opener for Mobile Phone for Opening Gates and Garages with Remote Control, x 4 Gates and up to 10 Users', NULL, 250.0, 1, 'Telefoane', 'Telefoane', NULL, 225.0, NULL, NULL, NOW(), NOW()),
  ('Cameră de supraveghere video wireless de interior EZVIZ CB2 1080P, vedere nocturnă, audio bidirecțional, albă', NULL, 150.0, 1, 'Smart Home', 'Camere supraveghere', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('Set 2 Camere Supraveghere Ezviz C6N Wi-Fi Full HD 1080p', NULL, 100.0, 1, 'Smart Home', 'Camere supraveghere', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('tomtom go classic 6inch Folosit', NULL, 400.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('tomtom go classic 2nd gen 5inch nou deschis', NULL, 350.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('tomtom go classic 2nd gen 5inch nou', NULL, 350.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('Casti wireless Jabra Pro 920, on-ear', NULL, 350.0, 1, 'Audio', 'Casti', 'Jabra', NULL, NULL, NULL, NOW(), NOW()),
  ('Casti Stereo Wireless UGREEN Studio Pro HP206, Bluetooth, A2DP, ANC', NULL, 100.0, 1, 'Audio', 'Casti', 'HP', NULL, NULL, NULL, NOW(), NOW()),
  ('Blink outdoor 4 camera+sync module 2', NULL, 600.0, 1, 'Foto & Video', 'Camere', 'Blink', NULL, NULL, NULL, NOW(), NOW()),
  ('Sonerie video eufy E340 Wireless Dual Camera, 2K HD, Negru', NULL, 300.0, 1, 'Smart Home', 'Camere supraveghere', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('Sonerie video eufy Wireless Dual Camera Add On 2K HD autonomie 6 luni Negru', NULL, 250.0, 1, 'Smart Home', 'Camere supraveghere', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('Camera de supraveghere eufycam S330 Add-on, 4K Ultra HD, BionicMind™, Nightvision, Incarcare solara', NULL, 500.0, 1, 'Smart Home', 'Camere supraveghere', NULL, NULL, NULL, NULL, NOW(), NOW()),
  ('Navigatie auto android/carplay carABC 7inch', NULL, 100.0, 1, 'Auto & Moto', 'GPS & Navigatie', NULL, 100.0, NULL, NULL, NOW(), NOW()),
  ('CarpodGo T3 Pro Portable 60fps Wireless Carplay Android Auto,8.9 Inch 1920 * 720 IPS Touch Screen Car Stereo,Display-Only BT Mode Supports Steering Wheel Controls', NULL, 500.0, 1, 'Auto & Moto', 'GPS & Navigatie', 'Ring', 300.0, NULL, NULL, NOW(), NOW()),
  ('Kodak Mini 3 retro 2x cartridge+ album', NULL, 400.0, 1, 'Foto & Video', 'Aparate foto', 'Kodak', NULL, NULL, NULL, NOW(), NOW()),
  ('Kodak cartridge paper 80 sheets foor photo printer deck', NULL, 75.0, 1, 'Foto & Video', 'Aparate foto', 'Kodak', NULL, NULL, NULL, NOW(), NOW()),
  ('Behringer UT300 ultr tremolo', NULL, 50.0, 1, 'Instrumente muzicale', 'Chitare & Efecte', 'Ring', 50.0, NULL, NULL, NOW(), NOW());
